### Recuperar todas las peliculas
GET http://localhost:1230/movies

### Recuperar una pelicula por ID
GET http://localhost:1230/movies/5ad1a235-0d9c-410a-b32b-220d91689a08

### Recuperar todas las peliculas de un género
GET http://localhost:1230/movies?genre=drama

### Crear una pelicula con POST
POST http://localhost:1230/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Actualizar una pelicula 
PATCH http://localhost:1230/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 2000
}